docker run -p6432:5432 -p6433:5433 -p6434:5434 -p6435:5435 -p6436:5436 ^
  --mount "type=bind,src=C:\ivolkov\dev\mail-all-cups\it_one_cup_sql/solution.sql,dst=/tmp/player1-solution.sql" ^
  --mount "type=bind,src=C:\ivolkov\dev\mail-all-cups\it_one_cup_sql/solution_v3b.sql,dst=/tmp/player2-solution.sql" ^
  --mount "type=bind,src=C:\ivolkov\dev\mail-all-cups\it_one_cup_sql/solution.sql,dst=/tmp/player3-solution.sql" ^
  --mount "type=bind,src=C:\ivolkov\dev\mail-all-cups\it_one_cup_sql/solution_v3b.sql,dst=/tmp/player4-solution.sql" ^
  --mount "type=bind,src=C:\ivolkov\dev\mail-all-cups\it_one_cup_sql/init.sql,dst=/tmp/init.sql" ^
  --mount "type=bind,src=C:\ivolkov\dev\mail-all-cups\it_one_cup_sql/R2-options.toml,dst=/tmp/options.toml" ^
  --rm -it -e SEED=345673 ghcr.io/all-cups/it_one_cup_sql ^
  --solution /tmp/player1-solution.sql ^
  --solution /tmp/player2-solution.sql ^
  --dump-init /tmp/init.sql ^
  --options /tmp/options.toml ^
  --log INFO ^
  --leave-running